<?xml version="1.0"?>
<package format="3">
  <name>drive_controller</name>
  <version>0.0.1</version>
  <description>Tracked motor control, encoder odometry, diagnostics, and passive calibration</description>
  <maintainer email="james.elsey@gmail.com">James Elsey</maintainer>
  <license>MIT</license>

  <buildtool_depend>python3-setuptools</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf_transformations</exec_depend>
  <exec_depend>python3-gpiozero</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
