<?xml version="1.0"?>
<package format="3">
  <name>joystick</name>
  <version>0.0.1</version>
  <description>Xbox teleoperation and voice-session controls</description>
  <maintainer email="james.elsey@gmail.com">James Elsey</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>senses</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
