frame_id: map
base_frame: base_link
rooms:
  room 1:
    polygon:
    - - -2.272
      - 1.272
    - - -1.872
      - 1.635
    - - -1.547
      - 1.397
    - - -1.822
      - 0.947
  room 2:
    polygon:
    - - -2.097
      - -0.641
    - - -1.347
      - -1.328
    - - -0.61
      - -0.728
    - - -1.097
      - 0.01
